# Identificação do projeto
sonar.projectKey=TouchRefletz_maia.api
sonar.projectName=maia.api
sonar.projectVersion=1.0.0

# Fontes de código para análise
sonar.sources=js,maia-api-worker/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/docs/**,**/act-artifacts/**,**/.wrangler/**

# Codificação
sonar.sourceEncoding=UTF-8
